version: "3.9"

services:
  db:
    image: postgres:16
    container_name: deal-intel-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aiintel
      POSTGRES_DB: dealintel
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  airbyte:
    image: ghcr.io/airbytehq/airbyte-ce:0.58.0
    container_name: deal-intel-airbyte
    ports:
      - "8000:8000"          # Web UI
      - "8001:8001"          # API
    environment:
      - AIRBYTE_ROLE=dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - airbyte_data:/data

volumes:
  db_data:
  airbyte_data: